### ISSUE TITLE
Add support for reading and writing CFF files

### ISSUE THREAD

**Issue by mfenner** [front-matter/briard#4]

**Comment by neteler** [comment]
I am happy to see the CFF support but struggle to use it:

```
briard https://doi.org/10.7554/elife.01567 -t CFF
Traceback (most recent call last):
	7: from /usr/local/bin/briard:23:in `<main>'
	6: from /usr/local/bin/briard:23:in `load'
	5: from /var/lib/gems/2.7.0/gems/briard-2.2.7/bin/briard:6:in `<top (required)>'
	4: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	3: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	2: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	1: from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.7.0/gems/briard-2.2.7/lib/briard/cli.rb:52:in `convert': undefined method `CFF' for #<Briard::Metadata:0x000056149e2ec2b0> (NoMethodError)
```

The [README](https://github.com/front-matter/briard/blob/master/README.md) isn't very clear (say, I do not expect white space to be used in a format name). What would be the correct name?

**Comment by neteler** [comment]
Ah, I see, it is "cff" (please consider to modify the entry in the README.md).

So I turn my comment into "result is empty" :-)

```
briard https://doi.org/10.5281/zenodo.2631917 -t cff
--> no result
```
